exclude:
  - "Gemfile"
  - "Gemfile.lock"
  - "LICENSE"
  - "README.md"
permalink: "/:title.html"
safe: "true"
sass:
  sass_dir: "assets/styles/_sass"
  style: "compressed"
  precision: "14"
  sourcemap: "none"
timezone: "America/Los_Angeles"
