baseurl: "/jekyll-boiler"
defaults:
  -
    scope:
      path: ""
      type: "drafts"
    values:
      layout: "post"
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
description: "Bare bones Jekyll example site using GitHub’s “pages” gem."
excerpt_separator: ""
exclude:
  - "bower_components"
  - "bower.json"
  - "Gemfile"
  - "LICENSE"
  - "node_modules"
  - "package.json"
  - "README.md"
gems:
  - jekyll-mentions
  - jemoji
  - jekyll-redirect-from
  - jekyll-sitemap
keywords: ["jekyll", "test", "boiler", "github", "pages"]
paginate: 1
paginate_path: "/:num/"
permalink: "/:title/"
relative_permalinks: "false"
safe: "true"
sass:
  sass_dir: "assets/styles/_includes"
  style: "compressed"
  precision: 14
  sourcemap: "none"
timezone: "America/Los_Angeles"
title: "Jekyll Boiler"
