baseurl: "/jekyll-test"
excerpt_separator: ""
exclude:
  - "Gemfile"
  - "Gemfile.lock"
  - "LICENSE"
  - "README.md"
gems:
- jekyll-mentions
- jemoji
- jekyll-redirect-from
- jekyll-sitemap
paginate: 25
paginate_path: "/:num/"
permalink: "/:title/"
relative_permalinks: "false"
safe: "true"
sass:
  sass_dir: "assets/styles/_sass"
  style: "compressed"
  precision: 14
  sourcemap: "none"
timezone: "America/Los_Angeles"
